version: "3.8"

services:
  api:
    build: .
    container_name: indicador_api
    restart: always
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - minio
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: indicador_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    #minio https://min.io/open-source/download?platform=docker
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Painel web (console)
    volumes:
      - minio-data:/data
      
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - app-network
    command: server --console-address ":9001" /data


volumes:
  pgdata:
  minio-data:


networks:
  app-network:
    driver: bridge
